#pragma once

// RGB config
#define RGB_ENABLED 1
#define NUM_LEDS 40
#define RGB_DATA_PIN GPIO_PINS_10
#define RGB_DATA_PORT GPIOA
#define RGB_DATA_PIN_SOURCE GPIO_PINS_SOURCE10
#define RGB_DATA_PIN_MUX GPIO_MUX_1
#define RGB_TIMER TMR1
#define RGB_TIMER_CLOCK CRM_TMR1_PERIPH_CLOCK
#define RGB_TIMER_CHANNEL TMR_SELECT_CHANNEL_3
#define RGB_TIMER_DMA_REQUEST TMR_C3_DMA_REQUEST
#define RGB_TIMER_DMAMUX_REQUEST DMAMUX_DMAREQ_ID_TMR1_CH3
#define RGB_DMA_CHANNEL DMA1_CHANNEL2
#define RGB_DMA_MUX_CHANNEL DMA1MUX_CHANNEL2
#define RGB_DMA_TRANSFER_FLAG DMA1_FDT2_FLAG
#define RGB_DMA_CLEAR_FLAG DMA1_GL2_FLAG
#define RGB_USE_BITBANG_DRIVER 1

// Joystick config
#define JOYSTICK_ENABLED 1
#define JOYSTICK_SW_PIN GPIO_PINS_9
#define JOYSTICK_SW_PORT GPIOA

#define JOYSTICK_X_ADC_INDEX 0
#define JOYSTICK_Y_ADC_INDEX 1
#define JOYSTICK_SW_KEY_INDEX 40
