#pragma once

// RGB config
#define RGB_ENABLED 1
#if !defined(MATRIX_PROCESSING_DIVIDER)
// Stable mode default: divider=4, ~8 kHz matrix/RT with ~32 kHz raw scan.
// Validation builds can override this to divider=2 for ~16 kHz matrix/RT.
#define MATRIX_PROCESSING_DIVIDER 4
#endif
#define MATRIX_SCHEDULER_MAX_CATCHUP_SCANS 4
#if !defined(MATRIX_SCHEDULER_BUDGET_US)
#define MATRIX_SCHEDULER_BUDGET_US 1000
#endif
#define ANALOG_SCAN_KEY_VERSION_DELTA 0
#if !defined(MATRIX_DETAILED_SCAN_DIAGNOSTICS)
#define MATRIX_DETAILED_SCAN_DIAGNOSTICS 0
#endif
#define MATRIX_IDLE_EMA_FAST_PATH 1
#define MATRIX_IDLE_RAW_FAST_PATH_MARGIN 24
#if !defined(MATRIX_LIVE_SCAN_TIMING_DIAGNOSTICS)
#define MATRIX_LIVE_SCAN_TIMING_DIAGNOSTICS 0
#endif
#define NUM_LEDS 40
#define RGB_DATA_PIN GPIO_PINS_10
#define RGB_DATA_PORT GPIOA
#define RGB_DATA_PIN_SOURCE GPIO_PINS_SOURCE10
#define RGB_DATA_PIN_MUX GPIO_MUX_1
#define RGB_TIMER TMR1
#define RGB_TIMER_CLOCK CRM_TMR1_PERIPH_CLOCK
#define RGB_TIMER_CHANNEL TMR_SELECT_CHANNEL_3
#define RGB_TIMER_DMA_REQUEST TMR_OVERFLOW_DMA_REQUEST
#define RGB_TIMER_DMAMUX_REQUEST DMAMUX_DMAREQ_ID_TMR1_OVERFLOW
#define RGB_DMA_CHANNEL DMA1_CHANNEL2
#define RGB_DMA_MUX_CHANNEL DMA1MUX_CHANNEL2
#define RGB_DMA_TRANSFER_FLAG DMA1_FDT2_FLAG
#define RGB_DMA_CLEAR_FLAG DMA1_GL2_FLAG
#define RGB_RESET_TIME_NS 300000ULL
#define RGB_DMA_FRAME_REPEATS 2u
#define RGB_BITBANG_FRAME_REPEATS 2u

// Joystick config
#define JOYSTICK_ENABLED 1
#define JOYSTICK_SW_PIN GPIO_PINS_9
#define JOYSTICK_SW_PORT GPIOA

#define JOYSTICK_X_ADC_INDEX 0
#define JOYSTICK_Y_ADC_INDEX 1
#define JOYSTICK_SW_KEY_INDEX 40
