#pragma once

#define SPI_NUM_BUSES 3

#define SPI_BUS0_INSTANCE SPI1
#define SPI_BUS0_CLOCK CRM_SPI1_PERIPH_CLOCK
#define SPI_BUS0_CLOCK_HZ 216000000
#define SPI_BUS0_SCK_PORT GPIOA
#define SPI_BUS0_SCK_PIN GPIO_PINS_5
#define SPI_BUS0_SCK_PIN_SOURCE GPIO_PINS_SOURCE5
#define SPI_BUS0_MISO_PORT GPIOA
#define SPI_BUS0_MISO_PIN GPIO_PINS_6
#define SPI_BUS0_MISO_PIN_SOURCE GPIO_PINS_SOURCE6
#define SPI_BUS0_MOSI_PORT GPIOA
#define SPI_BUS0_MOSI_PIN GPIO_PINS_7
#define SPI_BUS0_MOSI_PIN_SOURCE GPIO_PINS_SOURCE7
#define SPI_BUS0_PIN_MUX GPIO_MUX_5

#define SPI_BUS1_INSTANCE SPI2
#define SPI_BUS1_CLOCK CRM_SPI2_PERIPH_CLOCK
#define SPI_BUS1_CLOCK_HZ 108000000
#define SPI_BUS1_SCK_PORT GPIOB
#define SPI_BUS1_SCK_PIN GPIO_PINS_13
#define SPI_BUS1_SCK_PIN_SOURCE GPIO_PINS_SOURCE13
#define SPI_BUS1_MISO_PORT GPIOB
#define SPI_BUS1_MISO_PIN GPIO_PINS_14
#define SPI_BUS1_MISO_PIN_SOURCE GPIO_PINS_SOURCE14
#define SPI_BUS1_MOSI_PORT GPIOB
#define SPI_BUS1_MOSI_PIN GPIO_PINS_15
#define SPI_BUS1_MOSI_PIN_SOURCE GPIO_PINS_SOURCE15
#define SPI_BUS1_PIN_MUX GPIO_MUX_5

#define SPI_BUS2_INSTANCE SPI3
#define SPI_BUS2_CLOCK CRM_SPI3_PERIPH_CLOCK
#define SPI_BUS2_CLOCK_HZ 108000000
#define SPI_BUS2_SCK_PORT GPIOC
#define SPI_BUS2_SCK_PIN GPIO_PINS_10
#define SPI_BUS2_SCK_PIN_SOURCE GPIO_PINS_SOURCE10
#define SPI_BUS2_MISO_PORT GPIOC
#define SPI_BUS2_MISO_PIN GPIO_PINS_11
#define SPI_BUS2_MISO_PIN_SOURCE GPIO_PINS_SOURCE11
#define SPI_BUS2_MOSI_PORT GPIOC
#define SPI_BUS2_MOSI_PIN GPIO_PINS_12
#define SPI_BUS2_MOSI_PIN_SOURCE GPIO_PINS_SOURCE12
#define SPI_BUS2_PIN_MUX GPIO_MUX_6

#define TRACKBALL_ENABLED 1
#define TRACKBALL_SENSOR_PAW3395 1
#define TRACKBALL_SPI_BUS 2
#define TRACKBALL_CS_PORT GPIOC
#define TRACKBALL_CS_PIN GPIO_PINS_2
#define TRACKBALL_MOTION_PORT GPIOC
#define TRACKBALL_MOTION_PIN GPIO_PINS_3
#define TRACKBALL_SPI_FREQUENCY_HZ 8000000u
#define TRACKBALL_CPI_DEFAULT 1600
