#pragma once

// Run this reference target at 144 MHz so both ADC buses can land on an
// 18 MHz SPI clock with the AT32 power-of-two divider steps:
// SPI1: 144 / 8 = 18 MHz, SPI2: 72 / 4 = 18 MHz.
#define BOARD_PLL_NS 48u
#define BOARD_PLL_MS 1u
#define BOARD_PLL_FP CRM_PLL_FP_4
#define BOARD_PLL_FU CRM_PLL_FU_12
#define BOARD_APB2_DIV CRM_APB2_DIV_1
#define BOARD_APB1_DIV CRM_APB1_DIV_2

#define SPI_NUM_BUSES 2

#define SPI_BUS0_INSTANCE SPI1
#define SPI_BUS0_CLOCK CRM_SPI1_PERIPH_CLOCK
#define SPI_BUS0_CLOCK_HZ 144000000u
#define SPI_BUS0_SCK_PORT GPIOA
#define SPI_BUS0_SCK_PIN GPIO_PINS_5
#define SPI_BUS0_SCK_PIN_SOURCE GPIO_PINS_SOURCE5
#define SPI_BUS0_MISO_PORT GPIOA
#define SPI_BUS0_MISO_PIN GPIO_PINS_6
#define SPI_BUS0_MISO_PIN_SOURCE GPIO_PINS_SOURCE6
#define SPI_BUS0_MOSI_PORT GPIOA
#define SPI_BUS0_MOSI_PIN GPIO_PINS_7
#define SPI_BUS0_MOSI_PIN_SOURCE GPIO_PINS_SOURCE7
#define SPI_BUS0_PIN_MUX GPIO_MUX_5

#define SPI_BUS1_INSTANCE SPI2
#define SPI_BUS1_CLOCK CRM_SPI2_PERIPH_CLOCK
#define SPI_BUS1_CLOCK_HZ 72000000u
#define SPI_BUS1_SCK_PORT GPIOB
#define SPI_BUS1_SCK_PIN GPIO_PINS_13
#define SPI_BUS1_SCK_PIN_SOURCE GPIO_PINS_SOURCE13
#define SPI_BUS1_MISO_PORT GPIOB
#define SPI_BUS1_MISO_PIN GPIO_PINS_14
#define SPI_BUS1_MISO_PIN_SOURCE GPIO_PINS_SOURCE14
#define SPI_BUS1_MOSI_PORT GPIOB
#define SPI_BUS1_MOSI_PIN GPIO_PINS_15
#define SPI_BUS1_MOSI_PIN_SOURCE GPIO_PINS_SOURCE15
#define SPI_BUS1_PIN_MUX GPIO_MUX_5

#define SPI_ADC_BUS0_SCK_PORT GPIOA
#define SPI_ADC_BUS0_SCK_PIN GPIO_PINS_5
#define SPI_ADC_BUS0_MISO_PORT GPIOA
#define SPI_ADC_BUS0_MISO_PIN GPIO_PINS_6
#define SPI_ADC_BUS0_MOSI_PORT GPIOA
#define SPI_ADC_BUS0_MOSI_PIN GPIO_PINS_7

#define SPI_ADC_BUS1_SCK_PORT GPIOB
#define SPI_ADC_BUS1_SCK_PIN GPIO_PINS_13
#define SPI_ADC_BUS1_MISO_PORT GPIOB
#define SPI_ADC_BUS1_MISO_PIN GPIO_PINS_14
#define SPI_ADC_BUS1_MOSI_PORT GPIOB
#define SPI_ADC_BUS1_MOSI_PIN GPIO_PINS_15
