#pragma once

// RGB config
#define RGB_ENABLED 1
#define NUM_LEDS 40
#define RGB_DATA_PIN GPIO_PINS_10
#define RGB_DATA_PORT GPIOA
#define RGB_DATA_PIN_SOURCE GPIO_PINS_SOURCE10
#define RGB_DATA_PIN_MUX GPIO_MUX_1
#define RGB_TIMER TMR1
#define RGB_TIMER_CLOCK CRM_TMR1_PERIPH_CLOCK
#define RGB_TIMER_CHANNEL TMR_SELECT_CHANNEL_3
#define RGB_TIMER_DMA_REQUEST TMR_OVERFLOW_DMA_REQUEST
#define RGB_TIMER_DMAMUX_REQUEST DMAMUX_DMAREQ_ID_TMR1_OVERFLOW
#define RGB_DMA_CHANNEL DMA1_CHANNEL2
#define RGB_DMA_MUX_CHANNEL DMA1MUX_CHANNEL2
#define RGB_DMA_TRANSFER_FLAG DMA1_FDT2_FLAG
#define RGB_DMA_CLEAR_FLAG DMA1_GL2_FLAG
#define RGB_RESET_TIME_NS 300000ULL
#define RGB_DMA_FRAME_REPEATS 2u
#define RGB_BITBANG_FRAME_REPEATS 2u

// Trackball SPI config
#define SPI_NUM_BUSES 1

#define SPI_BUS0_INSTANCE SPI3
#define SPI_BUS0_CLOCK CRM_SPI3_PERIPH_CLOCK
#define SPI_BUS0_CLOCK_HZ 108000000
#define SPI_BUS0_SCK_PORT GPIOC
#define SPI_BUS0_SCK_PIN GPIO_PINS_10
#define SPI_BUS0_SCK_PIN_SOURCE GPIO_PINS_SOURCE10
#define SPI_BUS0_MISO_PORT GPIOC
#define SPI_BUS0_MISO_PIN GPIO_PINS_11
#define SPI_BUS0_MISO_PIN_SOURCE GPIO_PINS_SOURCE11
#define SPI_BUS0_MOSI_PORT GPIOC
#define SPI_BUS0_MOSI_PIN GPIO_PINS_12
#define SPI_BUS0_MOSI_PIN_SOURCE GPIO_PINS_SOURCE12
#define SPI_BUS0_PIN_MUX GPIO_MUX_6

// ADS7953 GPIO-SPI config
#define SPI_ADC_BUS0_SCK_PORT GPIOA
#define SPI_ADC_BUS0_SCK_PIN GPIO_PINS_0
#define SPI_ADC_BUS0_MISO_PORT GPIOA
#define SPI_ADC_BUS0_MISO_PIN GPIO_PINS_1
#define SPI_ADC_BUS0_MOSI_PORT GPIOC
#define SPI_ADC_BUS0_MOSI_PIN GPIO_PINS_3

#define SPI_ADC_BUS1_SCK_PORT GPIOA
#define SPI_ADC_BUS1_SCK_PIN GPIO_PINS_6
#define SPI_ADC_BUS1_MISO_PORT GPIOC
#define SPI_ADC_BUS1_MISO_PIN GPIO_PINS_4
#define SPI_ADC_BUS1_MOSI_PORT GPIOA
#define SPI_ADC_BUS1_MOSI_PIN GPIO_PINS_7

#if !defined(BOARD_DISABLE_TRACKBALL)
#define TRACKBALL_ENABLED 1
#define TRACKBALL_SENSOR_PAW3395 1
#define TRACKBALL_SPI_BUS 0
#define TRACKBALL_CS_PORT GPIOA
#define TRACKBALL_CS_PIN GPIO_PINS_15
#define TRACKBALL_MOTION_PORT GPIOD
#define TRACKBALL_MOTION_PIN GPIO_PINS_2
#define TRACKBALL_SPI_FREQUENCY_HZ 8000000u
#define TRACKBALL_CPI_DEFAULT 1600u
#endif

// Encoder config
#define ENCODER_NUM 1
#define ENCODER_A_PORTS {GPIOB}
#define ENCODER_A_PINS {GPIO_PINS_7}
#define ENCODER_B_PORTS {GPIOB}
#define ENCODER_B_PINS {GPIO_PINS_6}
// Set to {1} when using a sideways encoder such as an EC10 and the default
// clockwise/counterclockwise feel ends up reversed.
#define ENCODER_INVERT_DIRECTIONS {0}
#define ENCODER_INPUT_PULLUP
