# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <https://www.gnu.org/licenses/>.

"""Generate keyboards/<keyboard>/board_def.h from keyboard.json.

This script centralises the low-level hardware macros that previously lived in
a separate board_def.h file.  After running, the generated header is picked up
automatically by scripts/make.py.
"""

import os
import sys

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import utils


HEADER_TEMPLATE = """#pragma once

// DO NOT EDIT THIS FILE DIRECTLY
// This file is automatically generated from keyboards/{keyboard}/keyboard.json.
// Run `python setup.py -k {keyboard}` to regenerate it.

{content}
"""


def _add_guarded_define(lines: list[str], name: str, value: int | str):
    """Emit a #define wrapped in #if !defined(...) guards."""
    lines.extend(
        [
            f"#if !defined({name})",
            f"#define {name} {value}",
            "#endif",
        ]
    )


def _parse_simple_pin(pin: str) -> tuple[str, str]:
    """Parse a simple pin name such as 'A10' into (port, pin_macro).

    Returns ('GPIOA', 'GPIO_PINS_10').
    """
    if len(pin) < 2:
        raise ValueError(f"Invalid pin name: {pin}")
    port_letter = pin[0].upper()
    pin_number = pin[1:]
    if not pin_number.isdigit():
        raise ValueError(f"Invalid pin number in pin name: {pin}")
    return f"GPIO{port_letter}", f"GPIO_PINS_{pin_number}"


def _generate_matrix_section(matrix: dict) -> list[str]:
    lines: list[str] = []
    if not matrix:
        return lines

    lines.append("// Matrix config")

    if "processing_divider" in matrix:
        _add_guarded_define(lines, "MATRIX_PROCESSING_DIVIDER", matrix["processing_divider"])
    if "scheduler_max_catchup_scans" in matrix:
        _add_guarded_define(
            lines, "MATRIX_SCHEDULER_MAX_CATCHUP_SCANS", matrix["scheduler_max_catchup_scans"]
        )
    if "scheduler_budget_us" in matrix:
        _add_guarded_define(lines, "MATRIX_SCHEDULER_BUDGET_US", matrix["scheduler_budget_us"])
    if "adc_sample_delay_default" in matrix:
        _add_guarded_define(lines, "ADC_SAMPLE_DELAY_DEFAULT", matrix["adc_sample_delay_default"])
    if "analog_scan_key_version_delta" in matrix:
        _add_guarded_define(
            lines, "ANALOG_SCAN_KEY_VERSION_DELTA", matrix["analog_scan_key_version_delta"]
        )
    if "detailed_scan_diagnostics" in matrix:
        _add_guarded_define(
            lines, "MATRIX_DETAILED_SCAN_DIAGNOSTICS", matrix["detailed_scan_diagnostics"]
        )
    if "idle_raw_fast_path_margin" in matrix:
        _add_guarded_define(
            lines, "MATRIX_IDLE_RAW_FAST_PATH_MARGIN", matrix["idle_raw_fast_path_margin"]
        )
    if "live_scan_timing_diagnostics" in matrix:
        _add_guarded_define(
            lines, "MATRIX_LIVE_SCAN_TIMING_DIAGNOSTICS", matrix["live_scan_timing_diagnostics"]
        )

    lines.append("")
    return lines


def _generate_timings_section(timings: dict, processing_divider: int | None) -> list[str]:
    lines: list[str] = []
    if not timings:
        return lines

    lines.append("// Background task timings")
    # Defaults are calibrated for a specific processing divider.  When the
    # divider is overridden at compile time (e.g. matrix_div4 test builds) the
    # build flags must supply their own task timings.
    if processing_divider is not None:
        lines.append(f"#if MATRIX_PROCESSING_DIVIDER == {processing_divider}")

    for task, cfg in timings.items():
        task_upper = task.upper()
        _add_guarded_define(lines, f"HMK_{task_upper}_TASK_INTERVAL", cfg["interval"])
        _add_guarded_define(lines, f"HMK_{task_upper}_TASK_PHASE", cfg["phase"])

    if processing_divider is not None:
        lines.append("#endif")

    lines.append("")
    return lines


def _generate_rgb_section(rgb: dict, features: dict) -> list[str]:
    lines: list[str] = []
    if not rgb.get("hardware"):
        return lines

    hw = rgb["hardware"]
    lines.append("// RGB config")

    if features.get("rgb") or rgb.get("enabled"):
        _add_guarded_define(lines, "RGB_ENABLED", 1)

    if "num_leds" in hw:
        _add_guarded_define(lines, "NUM_LEDS", hw["num_leds"])

    if "data_pin" in hw:
        data_port, data_pin = _parse_simple_pin(hw["data_pin"])
        _add_guarded_define(lines, "RGB_DATA_PIN", data_pin)
        _add_guarded_define(lines, "RGB_DATA_PORT", data_port)

    # Optional derived pin macros; emit them only when the user supplied the
    # full macro name so the generated header can be bit-exact with legacy files.
    for json_key, macro_name in [
        ("data_pin_source", "RGB_DATA_PIN_SOURCE"),
        ("data_pin_mux", "RGB_DATA_PIN_MUX"),
    ]:
        if json_key in hw:
            _add_guarded_define(lines, macro_name, hw[json_key])

    if "timer" in hw:
        timer = hw["timer"]
        _add_guarded_define(lines, "RGB_TIMER", timer)
        _add_guarded_define(lines, "RGB_TIMER_CLOCK", f"CRM_{timer}_PERIPH_CLOCK")

    if "timer_channel" in hw:
        _add_guarded_define(lines, "RGB_TIMER_CHANNEL", hw["timer_channel"])

    for json_key, macro_name in [
        ("timer_dma_request", "RGB_TIMER_DMA_REQUEST"),
        ("timer_dmamux_request", "RGB_TIMER_DMAMUX_REQUEST"),
        ("dma_channel", "RGB_DMA_CHANNEL"),
        ("dma_mux_channel", "RGB_DMA_MUX_CHANNEL"),
        ("dma_transfer_flag", "RGB_DMA_TRANSFER_FLAG"),
        ("dma_clear_flag", "RGB_DMA_CLEAR_FLAG"),
    ]:
        if json_key in hw:
            _add_guarded_define(lines, macro_name, hw[json_key])

    if "reset_time_ns" in hw:
        _add_guarded_define(lines, "RGB_RESET_TIME_NS", f"{hw['reset_time_ns']}ULL")
    if "dma_frame_repeats" in hw:
        _add_guarded_define(lines, "RGB_DMA_FRAME_REPEATS", f"{hw['dma_frame_repeats']}u")
    if "bitbang_frame_repeats" in hw:
        _add_guarded_define(lines, "RGB_BITBANG_FRAME_REPEATS", f"{hw['bitbang_frame_repeats']}u")

    lines.append("")
    return lines


def _generate_joystick_section(joystick: dict) -> list[str]:
    lines: list[str] = []
    if not joystick:
        return lines

    lines.append("// Joystick config")

    if joystick.get("enabled"):
        _add_guarded_define(lines, "JOYSTICK_ENABLED", 1)

    if "sw_pin" in joystick:
        sw_port, sw_pin = _parse_simple_pin(joystick["sw_pin"])
        _add_guarded_define(lines, "JOYSTICK_SW_PIN", sw_pin)
        _add_guarded_define(lines, "JOYSTICK_SW_PORT", sw_port)

    if "x_adc_index" in joystick:
        _add_guarded_define(lines, "JOYSTICK_X_ADC_INDEX", joystick["x_adc_index"])
    if "y_adc_index" in joystick:
        _add_guarded_define(lines, "JOYSTICK_Y_ADC_INDEX", joystick["y_adc_index"])
    if "sw_key_index" in joystick:
        _add_guarded_define(lines, "JOYSTICK_SW_KEY_INDEX", joystick["sw_key_index"])

    lines.append("")
    return lines


def _format_c_array(values: list, dtype: str = "") -> str:
    """Format a Python list as a C array initializer."""
    parts = []
    for v in values:
        if isinstance(v, str):
            parts.append(v)
        elif isinstance(v, bool):
            parts.append("1" if v else "0")
        else:
            parts.append(str(v))
    return "{" + ", ".join(parts) + "}"


def _generate_clock_section(clock: dict) -> list[str]:
    lines: list[str] = []
    if not clock:
        return lines

    lines.append("// Clock config")
    for json_key, macro_name in [
        ("pll_ns", "BOARD_PLL_NS"),
        ("pll_ms", "BOARD_PLL_MS"),
        ("pll_fp", "BOARD_PLL_FP"),
        ("pll_fu", "BOARD_PLL_FU"),
        ("apb2_div", "BOARD_APB2_DIV"),
        ("apb1_div", "BOARD_APB1_DIV"),
    ]:
        if json_key in clock:
            value = clock[json_key]
            if json_key in ("pll_ns", "pll_ms"):
                value = f"{value}u"
            _add_guarded_define(lines, macro_name, value)

    lines.append("")
    return lines


def _generate_spi_section(spi: dict, driver: str) -> list[str]:
    lines: list[str] = []
    if not spi or not spi.get("buses"):
        return lines

    buses = spi["buses"]
    lines.append("// SPI bus config")
    _add_guarded_define(lines, "SPI_NUM_BUSES", len(buses))

    is_at32 = driver.startswith("at32")
    for idx, bus in enumerate(buses):
        prefix = f"SPI_BUS{idx}"
        instance = bus["instance"]
        _add_guarded_define(lines, f"{prefix}_INSTANCE", instance)
        if is_at32:
            _add_guarded_define(lines, f"{prefix}_CLOCK", f"CRM_{instance}_PERIPH_CLOCK")
        elif "clock_enable" in bus:
            _add_guarded_define(lines, f"{prefix}_CLOCK_ENABLE", bus["clock_enable"])
        if "clock_hz" in bus:
            _add_guarded_define(lines, f"{prefix}_CLOCK_HZ", bus["clock_hz"])

        sck_port, sck_pin = _parse_simple_pin(bus["sck_pin"])
        _add_guarded_define(lines, f"{prefix}_SCK_PORT", sck_port)
        _add_guarded_define(lines, f"{prefix}_SCK_PIN", sck_pin)

        if is_at32:
            pin_num = bus["sck_pin"][1:]
            _add_guarded_define(lines, f"{prefix}_SCK_PIN_SOURCE", f"GPIO_PINS_SOURCE{pin_num}")
        elif "sck_pin_af" in bus:
            _add_guarded_define(lines, f"{prefix}_SCK_PIN_AF", bus["sck_pin_af"])

        if "miso_pin" in bus:
            miso_port, miso_pin = _parse_simple_pin(bus["miso_pin"])
            _add_guarded_define(lines, f"{prefix}_MISO_PORT", miso_port)
            _add_guarded_define(lines, f"{prefix}_MISO_PIN", miso_pin)
            if is_at32:
                pin_num = bus["miso_pin"][1:]
                _add_guarded_define(
                    lines, f"{prefix}_MISO_PIN_SOURCE", f"GPIO_PINS_SOURCE{pin_num}"
                )

        if "mosi_pin" in bus:
            mosi_port, mosi_pin = _parse_simple_pin(bus["mosi_pin"])
            _add_guarded_define(lines, f"{prefix}_MOSI_PORT", mosi_port)
            _add_guarded_define(lines, f"{prefix}_MOSI_PIN", mosi_pin)
            if is_at32:
                pin_num = bus["mosi_pin"][1:]
                _add_guarded_define(
                    lines, f"{prefix}_MOSI_PIN_SOURCE", f"GPIO_PINS_SOURCE{pin_num}"
                )

        if is_at32 and "pin_mux" in bus:
            _add_guarded_define(lines, f"{prefix}_PIN_MUX", bus["pin_mux"])
        elif not is_at32 and "pin_af" in bus:
            _add_guarded_define(lines, f"{prefix}_PIN_AF", bus["pin_af"])

    lines.append("")
    return lines


def _generate_trackball_section(trackball: dict) -> list[str]:
    lines: list[str] = []
    if not trackball or not trackball.get("enabled"):
        return lines

    lines.append("// Trackball config")
    _add_guarded_define(lines, "TRACKBALL_ENABLED", 1)

    sensor = trackball["sensor"].upper()
    _add_guarded_define(lines, f"TRACKBALL_SENSOR_{sensor}", 1)

    _add_guarded_define(lines, "TRACKBALL_SPI_BUS", trackball["spi_bus"])

    cs_port, cs_pin = _parse_simple_pin(trackball["cs_pin"])
    _add_guarded_define(lines, "TRACKBALL_CS_PORT", cs_port)
    _add_guarded_define(lines, "TRACKBALL_CS_PIN", cs_pin)

    motion_port, motion_pin = _parse_simple_pin(trackball["motion_pin"])
    _add_guarded_define(lines, "TRACKBALL_MOTION_PORT", motion_port)
    _add_guarded_define(lines, "TRACKBALL_MOTION_PIN", motion_pin)

    if "spi_frequency_hz" in trackball:
        _add_guarded_define(lines, "TRACKBALL_SPI_FREQUENCY_HZ", f"{trackball['spi_frequency_hz']}u")
    if "cpi_default" in trackball:
        _add_guarded_define(lines, "TRACKBALL_CPI_DEFAULT", f"{trackball['cpi_default']}u")
    if "spi_hold_time_us" in trackball:
        _add_guarded_define(lines, "TRACKBALL_SPI_HOLD_TIME_US", trackball["spi_hold_time_us"])

    lines.append("")
    return lines


def _generate_encoder_hardware_section(encoder: dict) -> list[str]:
    lines: list[str] = []
    if not encoder or not encoder.get("map"):
        return lines

    hw = encoder.get("hardware")
    if not hw:
        return lines

    num = len(encoder["map"])
    a_pins = hw.get("a_pins", [])
    b_pins = hw.get("b_pins", [])
    if len(a_pins) != num or len(b_pins) != num:
        raise ValueError(
            f"encoder.hardware a_pins/b_pins length must match encoder.map length ({num})"
        )

    lines.append("// Encoder config")
    _add_guarded_define(lines, "ENCODER_NUM", num)

    a_ports = []
    a_pin_macros = []
    b_ports = []
    b_pin_macros = []
    for a, b in zip(a_pins, b_pins):
        a_port, a_pin = _parse_simple_pin(a)
        b_port, b_pin = _parse_simple_pin(b)
        a_ports.append(a_port)
        a_pin_macros.append(a_pin)
        b_ports.append(b_port)
        b_pin_macros.append(b_pin)

    invert = hw.get("invert_directions", [0] * num)
    if len(invert) != num:
        raise ValueError(
            f"encoder.hardware.invert_directions length must match encoder.map length ({num})"
        )

    _add_guarded_define(lines, "ENCODER_A_PORTS", _format_c_array(a_ports))
    _add_guarded_define(lines, "ENCODER_A_PINS", _format_c_array(a_pin_macros))
    _add_guarded_define(lines, "ENCODER_B_PORTS", _format_c_array(b_ports))
    _add_guarded_define(lines, "ENCODER_B_PINS", _format_c_array(b_pin_macros))
    _add_guarded_define(lines, "ENCODER_INVERT_DIRECTIONS", _format_c_array(invert))

    if hw.get("pullup"):
        lines.append("#if !defined(ENCODER_INPUT_PULLUP)")
        lines.append("#define ENCODER_INPUT_PULLUP")
        lines.append("#endif")

    lines.append("")
    return lines


def _generate_spi_adc_gpio_section(analog: dict) -> list[str]:
    lines: list[str] = []
    if not analog or analog.get("backend") != "spi_adc":
        return lines

    spi = analog.get("spi", {})
    buses = spi.get("buses", [])
    if not buses:
        return lines

    lines.append("// SPI ADC GPIO config")
    for bus in buses:
        gpio = bus.get("gpio")
        if not gpio:
            continue
        bus_idx = bus["bus"]
        prefix = f"SPI_ADC_BUS{bus_idx}"

        sck_port, sck_pin = _parse_simple_pin(gpio["sck_pin"])
        _add_guarded_define(lines, f"{prefix}_SCK_PORT", sck_port)
        _add_guarded_define(lines, f"{prefix}_SCK_PIN", sck_pin)

        miso_port, miso_pin = _parse_simple_pin(gpio["miso_pin"])
        _add_guarded_define(lines, f"{prefix}_MISO_PORT", miso_port)
        _add_guarded_define(lines, f"{prefix}_MISO_PIN", miso_pin)

        mosi_port, mosi_pin = _parse_simple_pin(gpio["mosi_pin"])
        _add_guarded_define(lines, f"{prefix}_MOSI_PORT", mosi_port)
        _add_guarded_define(lines, f"{prefix}_MOSI_PIN", mosi_pin)

    lines.append("")
    return lines


def generate_board_def(keyboard: str) -> str:
    kb_json = utils.get_kb_json(keyboard)

    matrix = kb_json.get("matrix", {})
    processing_divider = matrix.get("processing_divider")
    hardware = kb_json.get("hardware", {})
    driver = hardware.get("driver", "")

    sections: list[list[str]] = []
    sections.append(_generate_clock_section(hardware.get("clock", {})))
    sections.append(_generate_spi_section(hardware.get("spi", {}), driver))
    sections.append(_generate_spi_adc_gpio_section(kb_json.get("analog", {})))
    sections.append(_generate_matrix_section(matrix))
    sections.append(
        _generate_timings_section(hardware.get("timings", {}), processing_divider)
    )
    sections.append(
        _generate_rgb_section(kb_json.get("rgb", {}), kb_json.get("features", {}))
    )
    sections.append(_generate_trackball_section(kb_json.get("trackball", {})))
    sections.append(_generate_encoder_hardware_section(kb_json.get("encoder", {})))
    sections.append(_generate_joystick_section(kb_json.get("joystick", {})))

    content = "\n".join("\n".join(section).rstrip() for section in sections if section).rstrip()
    return HEADER_TEMPLATE.format(keyboard=keyboard, content=content)


def has_generated_board_def(kb_json: dict) -> bool:
    """Return True if keyboard.json contains the new board_def sections."""
    hardware = kb_json.get("hardware", {})
    return bool(
        kb_json.get("matrix")
        or hardware.get("timings")
        or hardware.get("spi")
        or hardware.get("clock")
        or kb_json.get("rgb", {}).get("hardware")
        or kb_json.get("trackball")
        or kb_json.get("encoder", {}).get("hardware")
        or kb_json.get("joystick")
        or (
            kb_json.get("analog", {}).get("backend") == "spi_adc"
            and kb_json.get("analog", {}).get("spi", {}).get("buses")
        )
    )


def write_board_def(keyboard: str):
    kb_json = utils.get_kb_json(keyboard)
    if not has_generated_board_def(kb_json):
        print(
            f"Skipping generated board_def.h for {keyboard}: "
            "keyboard.json does not contain board_def sections"
        )
        return

    output = generate_board_def(keyboard)
    output_path = os.path.join("keyboards", keyboard, "board_def.h")
    with open(output_path, "w") as f:
        f.write(output)
    print(f"Generated {output_path}")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print(f"Usage: {sys.argv[0]} <keyboard>", file=sys.stderr)
        sys.exit(1)
    write_board_def(sys.argv[1])
