# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <https://www.gnu.org/licenses/>.

import gzip
import json
import os
import utils
from keyboard_metadata import build_keyboard_metadata
from uuid import uuid4

METADATA_TEMPLATE = """#pragma once

#include "common.h"

// DO NOT EDIT THIS FILE DIRECTLY
// This file is automatically generated from `scripts/metadata.py`.

// GUID for Microsoft OS 2.0 descriptor
{ms_os_20_guid}

// Compressed keyboard metadata for the web configurator
{keyboard_metadata}
"""

Import("env")

keyboard = utils.get_keyboard_name(env)

kb_json = utils.get_kb_json(keyboard)
driver = utils.get_driver(keyboard)


def ms_os_20_guid_def():
    uuid = uuid4().hex.upper()
    guid = f"{{{uuid[:8]}-{uuid[8:12]}-{uuid[12:16]}-{uuid[16:20]}-{uuid[20:]}}}"
    guid_array = [f"U16_TO_U8S_LE('{x}')" for x in guid] + ["U16_TO_U8S_LE('\\0')"] * 2

    return utils.to_slice_def("MS_OS_20_GUID", guid_array)


def keyboard_metadata_def():
    metadata = build_keyboard_metadata(kb_json, driver)
    uncompressed = json.dumps(metadata).encode("utf-8")
    compressed = gzip.compress(uncompressed)
    print(f"Uncompressed metadata size: {len(uncompressed)} bytes")
    print(f"Compressed metadata size: {len(compressed)} bytes")

    return utils.to_slice_def("KEYBOARD_METADATA", compressed)


with open(os.path.join("include", "metadata.h"), "w") as f:
    f.write(
        METADATA_TEMPLATE.format(
            ms_os_20_guid=ms_os_20_guid_def(),
            keyboard_metadata=keyboard_metadata_def(),
        )
    )
