# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <https://www.gnu.org/licenses/>.

import gzip
import json
import os
import utils
from uuid import uuid4

METADATA_TEMPLATE = """#pragma once

#include "common.h"

// DO NOT EDIT THIS FILE DIRECTLY
// This file is automatically generated from `scripts/metadata.py`.

// GUID for Microsoft OS 2.0 descriptor
{ms_os_20_guid}

// Compressed keyboard metadata for the web configurator
{keyboard_metadata}
"""

Import("env")

keyboard = utils.get_keyboard_name(env)

kb_json = utils.get_kb_json(keyboard)
driver = utils.get_driver(keyboard)


def ms_os_20_guid_def():
    uuid = uuid4().hex.upper()
    guid = f"{{{uuid[:8]}-{uuid[8:12]}-{uuid[12:16]}-{uuid[16:20]}-{uuid[20:]}}}"
    guid_array = [f"U16_TO_U8S_LE('{x}')" for x in guid] + ["U16_TO_U8S_LE('\\0')"] * 2

    return utils.to_slice_def("MS_OS_20_GUID", guid_array)


def keyboard_metadata_def():
    num_keys = kb_json["keyboard"]["num_keys"]
    num_layers = kb_json["keyboard"]["num_layers"]

    features = kb_json.get("features", {})
    metadata_features = {
        "rgb": bool(features.get("rgb", False)),
        "joystick": bool(features.get("joystick", False)),
    }

    analog_keys = set()
    analog = kb_json.get("analog", {})
    mux = analog.get("mux", {})
    for row in mux.get("matrix", []):
        for key in row:
            if isinstance(key, int) and 0 <= key < num_keys:
                analog_keys.add(key)
    analog_keys = sorted(analog_keys)

    led_map = []
    led_coords = []
    mod_led_indices = []
    rgb = kb_json.get("rgb", {})
    if metadata_features["rgb"] and "led_map" in rgb:
        led_map = [key for key in rgb.get("led_map", []) if isinstance(key, int)]
        mod_keys = set(rgb.get("mod_keys", []))
        mod_led_indices = [
            led_index
            for led_index, key_index in enumerate(led_map)
            if key_index in mod_keys
        ]

        # Derive normalized LED coordinates from keyboard layout and LED map.
        key_coords = {}
        y_pos = 0.0
        for row in kb_json["layout"]["keymap"]:
            x_pos = 0.0
            for key_data in row:
                w = key_data.get("w", 1.0)
                h = key_data.get("h", 1.0)
                x_offset = key_data.get("x", 0.0)
                y_offset = key_data.get("y", 0.0)
                key_index = key_data.get("key")

                x_pos += x_offset
                y_pos += y_offset

                if key_index is not None:
                    key_coords[key_index] = (x_pos + w / 2.0, y_pos + h / 2.0)

                x_pos += w
            y_pos += 1.0

        if key_coords:
            min_x = min(coord[0] for coord in key_coords.values())
            max_x = max(coord[0] for coord in key_coords.values())
            min_y = min(coord[1] for coord in key_coords.values())
            max_y = max(coord[1] for coord in key_coords.values())
            range_x = max_x - min_x if max_x > min_x else 1.0
            range_y = max_y - min_y if max_y > min_y else 1.0

            for key_index in led_map:
                if key_index in key_coords:
                    x, y = key_coords[key_index]
                    led_coords.append(
                        {
                            "x": int((x - min_x) / range_x * 255),
                            "y": int((y - min_y) / range_y * 255),
                        }
                    )
                else:
                    led_coords.append({"x": 0, "y": 0})

    metadata = {
        "name": kb_json["name"],
        "vendorId": kb_json["usb"]["vid"],
        "productId": kb_json["usb"]["pid"],
        "usbHighSpeed": kb_json["usb"]["port"] == "hs",
        "adcResolution": utils.get_adc_resolution(kb_json, driver),
        "numProfiles": kb_json["keyboard"]["num_profiles"],
        "numLayers": num_layers,
        "numKeys": num_keys,
        "numAdvancedKeys": kb_json["keyboard"]["num_advanced_keys"],
        "features": metadata_features,
        "layout": kb_json["layout"],
        "analogKeys": analog_keys,
        "ledMap": led_map,
        "ledCoords": led_coords,
        "modLedIndices": mod_led_indices,
        "defaultKeymaps": utils.resolve_default_keymaps(kb_json),
    }

    uncompressed = json.dumps(metadata).encode("utf-8")
    compressed = gzip.compress(uncompressed)
    print(f"Uncompressed metadata size: {len(uncompressed)} bytes")
    print(f"Compressed metadata size: {len(compressed)} bytes")

    return utils.to_slice_def("KEYBOARD_METADATA", compressed)


with open(os.path.join("include", "metadata.h"), "w") as f:
    f.write(
        METADATA_TEMPLATE.format(
            ms_os_20_guid=ms_os_20_guid_def(),
            keyboard_metadata=keyboard_metadata_def(),
        )
    )
